version: '3'
services:
  api:
    build: ./api
    ports:
      - "5005:5005"
    depends_on:
      - service1
      - service2
      - service3
      - postgres
    volumes:
      - ./api:/app

  service1:
    build: ./service1
    depends_on:
      - postgres
    volumes:
      - ./service1:/app

  service2:
    build: ./service2
    depends_on:
      - postgres
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./service2:/app

  service3:
    build: ./service3
    depends_on:
      - postgres
    volumes:
      - ./service3:/app

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}