version: '3'
services:
  api:
    build: ./api
    ports:
      - "5005:5005"
    depends_on:
      - service1
      - service2
      - service3
      - postgres
    volumes:
      - ./api:/app

  service1:
    build: ./service1
    depends_on:
      - postgres
    volumes:
      - ./service1:/app

  service2:
    build: ./service2
    depends_on:
      - postgres
    volumes:
      - ./service2:/app

  service3:
    build: ./service3
    depends_on:
      - postgres
    volumes:
      - ./service3:/app

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
